### ISSUE TITLE
pypy2

### ISSUE THREAD

**Issue by jayvdb** [ymyzk/tox-gh-actions#116]
**Describe the bug**
The docs here suggest using `pypy-2.7: pypy2-..`, however I believe it should be `pypy-2.7: pypy-..`.

Using 'pypy2' results in

```
| Running tox with tox-gh-actions
| $ tox
[CI/test]   ❓  ::add-matcher::/opt/hostedtoolcache/PyPy/2.7.18/x64/site-packages/tox_gh_actions/matcher.json
| No handlers could be found for logger "filelock"
| GLOB sdist-make: /Users/jayvdb/django/django-rest-framework-braces/setup.py
| pypy2-django11-drflatest create: /Users/jayvdb/django/django-rest-framework-braces/.tox/pypy2-django11-drflatest
| ::group::tox: pypy2-django11-drflatest
| ERROR: InterpreterNotFound:
| ___________________________________ summary ____________________________________
| ERROR:  pypy2-django11-drflatest: InterpreterNotFound:
| ::remove-matcher owner=tox-gh-actions-warning-error::
```

**Comment by ymyzk** [comment]
Hello, thanks for filing a ticket. tox-gh-actions itself is actually using `pypy-2: pypy2` and working correctly. https://github.com/ymyzk/tox-gh-actions/blob/2a9fdfcb4f591f229b5d576f5399087950fe923a/setup.cfg#L99

https://github.com/dealertrack/django-rest-framework-braces/pull/33/files is the PR you're working on? I can have a deeper look later when I have time to understand what's happening.

**Comment by jayvdb** [comment]
Yes, that is where I encountered it.
Thanks for looking.
