### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by hynek** [ymyzk/tox-gh-actions#16]
Do you have any plans for adding support for pypy2 and pypy3? This is the only thing that stops me from using tox-gh-actions right now.

Let me know if I can help you with that in any way!

**Comment by ymyzk** [comment]
@hynek, thanks for a suggestion! Considering that GitHub Action officially provides PyPy 2 and 3, it's nice to support them with tox-gh-actions as well. I'll add support in #18.

**Comment by ymyzk** [comment]
This is now published to PyPI as v1.1.0
