### ISSUE TITLE
emit ::group tags

### ISSUE THREAD

**Issue by graingert** [ymyzk/tox-gh-actions#32]
https://github.com/actions/toolkit/blob/1cc56db0ff126f4d65aeb83798852e02a2c180c3/docs/commands.md#group-and-ungroup-log-lines

see https://github.com/tox-dev/action/issues/1
see https://github.com/tox-dev/tox-travis/issues/152
see https://github.community/t/log-group-multiplexing/130543

**Comment by ymyzk** [comment]
Sounds like an interesting feature to support. Let me consider adding this.
