### ISSUE TITLE
Great addtion to the tox ecosystem (tox-dev adoption)

### ISSUE THREAD

**Issue by ssbarnea** [ymyzk/tox-gh-actions#57]
While I did not used this action yet, I was contemplating the idea for a very long time, as most of my projects are pure python and already using tox. This action is supposed to save us a huge amount of time maintaining, the unfriendly, github actions pipelines.

As tox4 work is progressing and is introducing notable changes, I wonder if it would not be a good idea to host this project under the @tox-dev organization, alongside other tox related projects, including plugins and CI/CD helpers.

**Comment by ymyzk** [comment]
Thank you for your feedback, @ssbarnea! Hosting tox-gh-actions under @tox-dev is an interesting idea. I think there's pros and cons on hosting this project under the tox organization. At this point, my workload to keep maintaining the project is low enough to continue this project personally so moving the code is not high priority at this point.

I'd like to keep this issue open and get more feedback from others if there is. I may change my mind in the near future :)

**Comment by walles** [comment]
FWIW there is another similar project already under @tox-dev:

<https://github.com/tox-dev/tox-gh>

**Comment by ssbarnea** [comment]
@walles I guess you found the answer, go official for far less less risks.

**Comment by gaborbernat** [comment]
Must be noted though tox-gh only supports the new tox 4 version, and has a slightly different support table.
