### ISSUE TITLE
tox v4 support

### ISSUE THREAD

**Issue by ymyzk** [ymyzk/tox-gh-actions#59]
tox v4 is work in progress at https://github.com/tox-dev/tox/tree/rewrite. It says

> Compatibility wise we aim to be (excluding some weird edge cases) configuration file compatible with tox 3. We'll not be API compatible though (all plugins will break).

so we'll likely need to make some changes. It seems the new API for plugins is not well documented at this point. We can start working on this later.

---

Plan for tox v4 support:

- Preparation
  - [x] Drop Python 2.7 and 3.5 support
  - [x] Remove deprecated features: old-style PyPy key
  - [x] Use annotations for type hints
  - [x] Remove pytest v5
- tox v4 support
  - [x] Initial support
  - [x] Improve test coverage
  - [x] Update documentation
  - [x] Support log line grouping
- Release
  - [x] Release tox-gh-actions v3.0.0a1 which is tested with tox v4.0.0a9 
  - [x] Release tox-gh-actions v3.0.0 once tox v4.0.0 is released

**Comment by jezdez** [comment]
Thanks for tracking this @ymyzk! This might interest you: https://twitter.com/gjbernat/status/1369308331521740815

**Comment by gaborbernat** [comment]
Part of the issue here is that tox-gh-actions assume tox can run under all target python versions. This is no longer true, so we'd need to have an else branch for old python versions.

**Comment by gaborbernat** [comment]
superseded by https://github.com/ymyzk/tox-gh-actions/issues/74

**Comment by ymyzk** [comment]
https://github.com/ymyzk/tox-gh-actions/releases/tag/v3.0.0 is released.
